# continuous integration

# run tests for repo

---
name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.9

    # Service containers to run with `container-job`
    steps:
      - uses: actions/checkout@v1
      - name: Install test runner
        run: python3 -m pip install tox
      - name: Run tests
        run: tox

